import Head from 'next/head'
import Header from '../components/Header'

export default function labs() {
    return (
        <>
            <Head>
                <title>Verst.io</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="App">

                Labs
            </div>
        </>
    )
}
